# Generated by Django 3.1.1 on 2021-10-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='ontent',
            new_name='content',
        ),
    ]
